### ISSUE TITLE
Error in kuenm_cal(occ.joint = occ_joint, occ.tra = occ_tra, M.var.dir = M_var_dir,  :    unused argument (args = args)

### ISSUE THREAD

**Issue by EnriqueCasasMas** [marlonecobos/kuenm#1]
Hello everyone!
After installing all necessary software and ckecking requirements (everything working fine) to run KUENM, I keep getting this message when running the script:

Error in kuenm_cal(occ.joint = occ_joint, occ.tra = occ_tra, M.var.dir = M_var_dir,  : 
  unused argument (args = args)

My script is just identical to the example one:

setwd("C:/Users/MSI/Desktop/ku.enm_example_data/A_americanum")
library(kuenm)
help(kuenm_start)

occ_joint <- "aame_joint.csv"
occ_tra <- "aame_train.csv"
M_var_dir <- "M_variables"
batch_cal <- "Candidate_models"
out_dir <- "Candidate_Models"
reg_mult <- c(seq(0.1, 1, 0.1), seq(2, 6, 1), 8, 10)
f_clas <- "all"
args <- "maximumbackground = 30000"  # e.g., "maximumbackground=20000" 
maxent_path <- "C:/Users/MSI/Desktop/ku.enm_example_data/A_americanum"
wait <- FALSE
run <- TRUE

kuenm_cal(occ.joint = occ_joint, occ.tra = occ_tra, M.var.dir = M_var_dir, batch = batch_cal,
          out.dir = out_dir, reg.mult = reg_mult, f.clas = f_clas, args = args,
          maxent.path = maxent_path, wait = wait, run = run)

I am using the example data with the proper folder organization.
I am using R version 3.4.4

Does anybody know what could this be?

Thank you very much for your time.

**Comment by marlonecobos** [comment]
Hi @EnriqueCasasMas, 
Please try to install the new version of the package, restart your session, reload the package and try again. If during the installation you are asked to update packages, please do it. If any of the packages gives an error, please install it alone using install.packages(), then try reinstalling kuenm again. Also, it may be a good idea to update R and Rstudio (if you are using it). Please let me know if the problem persists after that.

**Comment by EnriqueCasasMas** [comment]
It worked!
Thank you very much for your quick response and your help!
