### ISSUE TITLE
Issue with kuenm_modstats after kuenm_mod_swd

### ISSUE THREAD

**Issue by pablofcuervo** [marlonecobos/kuenm#10]
Hi Marlon,
Thanks in advance for your advice and the great job done with kuenm!

After calibrating and evaluating a set of models with "kuenm_cal_swd, I'd transfered the selected models to the calibration area with no extrapolation (as kuenm_cal_swd does not provide a geographical projection to the calibration area). Right now, I'm willing to calculate statistics from those models with "kuenm_modstats", but I'm getting the following error:

"Preparing data for starting analyses, please wait...
Error in x[[1]] : subíndice fuera de  los límites"

sp_name <- 'Amblyomma_tigrinum'
fmod_dir <- 'Final_models'
stats <- c('med', 'range', 'sd')
scenarios <- 'calibration'
ext_type <- 'NE'

kuenm::kuenm_modstats(sp.name = sp_name, fmod.dir = fmod_dir, format = 'asc', project = TRUE, 
               statistics = stats, replicated = TRUE, proj.scenarios = scenarios, 
               ext.type = ext_type, out.dir = 'Final_model_stats')

I've successfully applied most of these functions, but is the first time I'm using the SWD functions (after seeing your presentation about kuenm in the ENM2020 course), yet being unable to find the problem when calculating statistics.

Regards,

Pablo

**Comment by marlonecobos** [comment]
Thanks for your feedback on using the package, Unfortunately, I haven't finished implementing post-modeling analyses for models prepared using the SWD format. That should take me a few days, but given my other duties, it can be a little longer. If you are not in a hurry, in August those post-modeling functions should be ready to work with SWD outputs in kuenm. I will comment in this issue once they are ready.

**Comment by pablofcuervo** [comment]
Thanks Marlon! There's no hurry... in the meantime, I'll implement some shortcuts to this in order to continue working, and then will include the appropriate kuenm function.

Regards

**Comment by marlonecobos** [comment]
Hi, the function kuenm_modstats_swd should solve the problem. The function kuenm_mmop has a new argument "is.swd" that helps solving the problem when the format swd is used. Also, the functions that help to summarize variability will also be changed soon.
