### ISSUE TITLE
Warning with mutate function from dplyr

### ISSUE THREAD

**Issue by aleferreiro** [marlonecobos/kuenm#12]
Hi! I am struggling cause i am trying to use the package to run some analysis, but when I am using the function kuenm_mod to run models selected, I am getting only one replicate of the maxent run and not the 10 that i had called. I guess that the problem is related to the following warning that I get after running the function kuenm_ceval:

*Warning messages:*
1: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. **

Thanks in advance

**Comment by Anel1982** [comment]
Hola, descargué la versión más reciente de Kuem y cada que utilizo la función kuenm_cal() me sale el error " Startup parameters not understood: autofeature, linear, quadratic, product, threshold, hinge, 10000, extrapolate, doclamp, replicatetype, plots, outputformat, warnings, vissible"
Si le doy aceptar me crea el primer modelo y luego sale de nuevo el error tantas veces como cantidad de modelos se creen.
Cómo puedo solucionar esto?
Gracias de antemano

**Comment by SebastiaJaumeRamis** [comment]
Hello, 

I have the same problem as @aleferreiro 

Warning message:
`mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 

backtrace:
  1. kuenm::kuenm_ceval(...)
 10. dplyr::mutate_(...)
 11. dplyr:::lazy_deprec("mutate")

How can I fix it? According to the maxent.log comment, how can I find in which candidate model occurs the error? 

Tank you!

**Comment by marlonecobos** [comment]
Hola @Anel1982, no vi esto antes. Puedes decirme si se resolvió de alguna manera, sino, puedes decirme que versión de Maxent estas utilizando?

**Comment by marlonecobos** [comment]
Hi @SebastiaJaumeRamis, do not worry about the warning from mutate(), I will fix that eventually, but until now that is not a problem for your results.
