### ISSUE TITLE
Projecting model in SWD mode

### ISSUE THREAD

**Issue by jmburgos** [marlonecobos/kuenm#15]
Hi Marlon,

I  am a bit confused about how to project a model fitted in SWD format.  To train the model I used the `kuenm_cal_swd` function, which uses data files created with the` prepare_swd` function.  So far so good.  To do the projection with `kuenm_cal_swd`, I need to set `project=TRUE` and add the path to the G.var.dir directory.  Does this directory contains the prediction layers as ascii rasters?  Or do I need to create SWD files here too?  If so, how do I do it?

Many thanks for the clarifications,

Julian

**Comment by jmburgos** [comment]
Ok, I have tried setting `project=TRUE` and using a `G.var.dir` directory with ascii rasters.   This does not seem to work.  The bash script generated to run the models is as follows:

```
#! /bin/csh
 java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/Boars_background/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models2/M_0.1_F_lq_Set_1_EC" betamultiplier=0.1 autofeature=false linear=true quadratic=true product=false threshold=false hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=true doclamp=true writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
  java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/Boars_background/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models2/M_0.1_F_lq_Set_1_E" betamultiplier=0.1 autofeature=false linear=true quadratic=true product=false threshold=false hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=true doclamp=false writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
  java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/Boars_background/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models2/M_0.1_F_lq_Set_1_NE" betamultiplier=0.1 autofeature=false linear=true quadratic=true product=false threshold=false hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=false doclamp=false writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
```
Note that the `projectionlayers=` argument is not assigned.

**Comment by marlonecobos** [comment]
Hi Julian,

You will have to set your `G.var.dir` directory differently. Since kuenm allows you to use distinct sets of environmental layers for model calibration, it also requires you to follow that idea when doing projections. Therefore you will need to create a folder called Set_1 (in your case) inside your folder G_variables (or the name you used for `G.var.dir` in your working directory). 

Also, because we wanted to allow for multiple projections to be made at the time, inside your G_variables--Set_1 folder, you need to have subfolders containing the ascii layers.

Something like this:

Gvariables -- Set_1 
                               -- scenario_1 -- var1.asc, var2.asc, var3.asc, var4.asc
                               -- scenario_2 -- var1.asc, var2.asc, var3.asc, var4.asc

You can add as many scenarios as you want inside G_variables -- Set_1. If you are projecting to another time scenario you would like to add a folder containing the current scenario for your region of interest. If you need to have a raster layer for the calibration area, you would probably like to add a folder with ascii layers for that region as well.

I hope it helps.

**Comment by jmburgos** [comment]
Thank you Marlon.  I haven't been able to project the model yet.  There is something missing and I cannot figure it out.

To recall, I fitted my model in SWD mode, using a single set of predictor variables:

`./M_variables/Set_1.csv`

I am projecting into a single scenario (a different geographical area), so the set up of my G_variables following your recommendation like this:
```
./G_variables/Set_1/Scenario_1/PC1.asc
./G_variables/Set_1/Scenario_1/PC2.asc
./G_variables/Set_1/Scenario_1/PC3.asc
./G_variables/Set_1/Scenario_1/PC4.asc
./G_variables/Set_1/Scenario_1/PC5.asc
```
I run the projection with the following call:
```
kuenm_mod_swd(occ.joint = "Boars_SWD_joint.csv",
              back.dir = "M_variables",
              out.eval = "Candidate_models_eval",
              batch = "Final_models",
              rep.n = 5,
              rep.type = "Bootstrap",
              out.format = "cloglog",
              jackknife = FALSE,
              write.mess = TRUE,
              write.clamp = TRUE,
              maxent.path ="/home/sjor/julian/Boars_kuenm",
              out.dir = "Final_models",
              project = TRUE,
              G.var.dir="/home/sjor/julian/Boars_kuenm/G_variables/Set_1/")
```

Still, the `Candidate_models.sh` script does not includes the path to the projection layers:

```
#! /bin/csh
 java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/M_variables/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models/M_2.5_F_lqpt_Set_1_EC" betamultiplier=2.5 autofeature=false linear=true quadratic=true product=true threshold=true hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=true doclamp=true writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
 java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/M_variables/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models/M_2.5_F_lqpt_Set_1_E" betamultiplier=2.5 autofeature=false linear=true quadratic=true product=true threshold=true hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=true doclamp=false writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
 java -mx1000m -jar "/home/sjor/julian/Boars_kuenm/maxent.jar" environmentallayers="/home/sjor/julian/Boars_kuenm/M_variables/Set_1.csv" samplesfile="/home/sjor/julian/Boars_kuenm/Boars_SWD_joint.csv" projectionlayers= outputdirectory="/home/sjor/julian/Boars_kuenm/Final_models/M_2.5_F_lqpt_Set_1_NE" betamultiplier=2.5 autofeature=false linear=true quadratic=true product=true threshold=true hinge=false replicates=5 replicatetype=Bootstrap jackknife=false outputformat=cloglog extrapolate=false doclamp=false writeclampgrid=true writemess=true responsecurves=true  warnings=false visible=false autorun
```
As before , in my `Final_models` I get three folders labeled "E", "EC" and "NE" (I am not sure what these labels mean).  The prediction in the three folders is the same, showing only the predicted suitability in the callibration area.

**Comment by marlonecobos** [comment]
Hi Julian, sorry it took so long to answer. 

The labels  "E", "EC", and "NE", represent the way Maxent extrapolates to environmental conditions non-analogous to those in the area of model calibration. E = free extrapolation, EC = extrapolation with clamping, and NE = no extrapolation. This is in the function documentation.

Please try to add the name of `G.var.dir` using only the path starting from your current working directory. In your case, it should be "G_variables" only. 

Best.

**Comment by jmburgos** [comment]
Hi Marlon,
No worries. Thanks for the clarification, I should read the documentation more carefully.  I think it the projection is is running now.  You will get an acknowledgment in our paper. :)
One last question.  We are interested in obtaing model output (predicted suitability, model performance metrics, etc.) both for the model calibration area, and the projection area.  In our case we these are two separate geographic region.  When you use `project=TRUE` in the `kuenm_mod_swd` function, you get them only for the projection area.  What would be the best way to obtain model output for both areas?  Should I put the predictors from the calibration area as one of the scenarios for the projection?

**Comment by marlonecobos** [comment]
Hi Julian,

Yes, include the raster layers for the calibration area as another scenario. I would call it "calibration". Best.

**Comment by marlonecobos** [comment]
Thanks for sharing your questions. Closing this issue.
