### ISSUE TITLE
I can't install kuenm

### ISSUE THREAD

**Issue by KevinLopezReyes** [marlonecobos/kuenm#2]
Hello Marlon, Good night,

I´m trying to install kuenm

if(!require(devtools)){
    install.packages("devtools")
}

if(!require(kuenm)){
    devtools::install_github("marlonecobos/kuenm")
}

but I have this error:

Error: package or namespace load failed for 'kuenm' in namespaceExport(ns, exports):
 undefined exports: to_closest
Error: loading failed
Ejecución interrumpida
*** arch - x64
Error: package or namespace load failed for 'kuenm' in namespaceExport(ns, exports):
 undefined exports: to_closest
Error: loading failed
Ejecución interrumpida
ERROR: loading failed for 'i386', 'x64'
removing 'C:/Users/52999/Documents/R/win-library/3.6/kuenm'
Error: Failed to install 'kuenm' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/52999/AppData/Local/Temp/RtmpQ9zVLV/file34c1420622d/kuenm_1.1.3.tar.gz’ had non-zero exit status

Thank you for your time,

Kevin

**Comment by sahmoli** [comment]
I had the same problem when installing kuenm.

**Comment by marlonecobos** [comment]
Hi, guys (@KevinLopezReyes and @sahmoli ),

Thanks a lot for telling me. The error must be fixed now. Please try installing it again and tell me if it works.

Best,

**Comment by sahmoli** [comment]
It works now. Thank you so much.
