### ISSUE TITLE
Analysis in other spatial projections?

### ISSUE THREAD

**Issue by jmburgos** [marlonecobos/kuenm#20]
Hi Marlon,

I am planning on running some models in high latitudes, and my data (observations and environmental predictors) are in a projected system ( Lamberts Equal Area projection) as opposed to be in "regular" latitude and longitude.  My models are big, so I need to run them in SWD mode.  The SWD files have columns named "latitude" and "longitude", but I presume that it should not matter if the values in these columns are actual degrees, or numbers in any other projected system, correct?  Or for some reason is a requirement that the data is converted to latitude/longitude values?

Many thanks,

Julian

**Comment by marlonecobos** [comment]
Hi @jmburgos, I think maxent requires the data to be in WGS84. But I am not completely sure. You can always try. The other option is to change the projection of your data and variables, that should not be a problem if you use packages like sp and raster.

I hope it helps.

**Comment by jmburgos** [comment]
Thanks Marlon, actually it should not matter in which projection you are working.  Maxent fits the model in environmental space and (as far as I know) the spatial projection of the observation should not be relevant.  I have been doing models in large areas in the Arctic using the Lamberts projection and they work well.  I was actually asking if there was something in kuenm that assumed that the positions were in WGS84.
