### ISSUE TITLE
jackknife modelo final

### ISSUE THREAD

**Issue by MontserratC** [marlonecobos/kuenm#24]
Hola tengo problemas al intentar hacer jackknife en mi modelo final, aunque pongo TRUE en la parametrización, no me aparece, y el archivo de resultados de maxent, me aparece vacío, no se como corregirlo o si tengo un bug, espero puedan ayudarme

Saludos
Gracias!

**Comment by marlonecobos** [comment]
This is really old, but the problem should be solved now.
