### ISSUE TITLE
Can it be true that the vignette creates 1581 calibration models for A_americanum in the tutorial 

### ISSUE THREAD

**Issue by kamaulindhardt** [marlonecobos/kuenm#25]
In the vignette's function `kuenm_cal()` I get 1581 calibration model, that I find quite a lot. In addition it slows down my calculations. Any idea?

```
If asked and run = TRUE, allow running as administrator.
Process finished
A maxent shell script for creating 1581 calibration models has been written
Check your working directory!!!    /Users/kamaulindhardt_1/Library/Mobile Documents/com~apple~CloudDocs/MSc Wageningen University /Internship ICRAF-ERA/R notes, codes and content/kuenm-master
bash: /Users/kamaulindhardt_1/Library/Mobile: No such file or directory
```

I have specified variables and arguments exactly as in the vignettes 

#### Candidate models

Candidate models are a large set of candidate models created to respond to the need to test broad suites of parameter combinations, such as, distinct regularization multiplier values, various feature classes, and different sets of environmental variables. The following code calls the help page of the function kuenm_cal.

```{r, eval=FALSE}
help(kuenm_cal)
```

```{r}
setwd("/Users/kamaulindhardt_1/Library/Mobile Documents/com~apple~CloudDocs/MSc Wageningen University /Internship ICRAF-ERA/R notes, codes and content/kuenm-master/ku.enm_example_data")
```

<br>

The next chunk of code is for preparing the arguments to use the function. These variables should be changed according to each case.

```{r, eval=FALSE}
# Variables with information to be used as arguments. Change "YOUR/DIRECTORY" by your actual directory.
occ_joint <- "./ku.enm_example_data/A_americanum/aame_joint.csv"
occ_tra <- "./ku.enm_example_data/A_americanum/aame_train.csv"
M_var_dir <- "./ku.enm_example_data/A_americanum/M_variables/"
batch_cal <- "./ku.enm_example_data/A_americanum/Candidate_models"
out_dir <- "./ku.enm_example_data/A_americanum/Candidate_Models"
reg_mult <- c(seq(0.1, 1, 0.1), seq(2, 6, 1), 8, 10)
f_clas <- "all"
args <- NULL # e.g., "maximumbackground=20000" for increasing the number of pixels in the bacground or
             # note that some arguments are fixed in the function and should not be changed
maxent_path <- "/Users/kamaulindhardt_1/Library/Mobile Documents/com~apple~CloudDocs/MSc Wageningen University /Internship ICRAF-ERA/R notes, codes and content/kuenm-master/ku.enm_example_data/A_americanum"
wait <- FALSE
run <- TRUE
```

<br>

The following is the code for using the function.

```{r, eval=FALSE}
kuenm_cal(occ.joint = occ_joint, occ.tra = occ_tra, M.var.dir = M_var_dir, 
          batch = batch_cal, out.dir = out_dir, reg.mult = reg_mult, 
          f.clas = f_clas, args = args, maxent.path = maxent_path, max.memory = 1000,
          wait = wait, run = run)
```

**Comment by kamaulindhardt** [comment]
As you see I also get the error issue

`bash: /Users/kamaulindhardt_1/Library/Mobile: No such file or directory`

Why is that?

**Comment by kamaulindhardt** [comment]
How do I get the window of the evaluation process to show progress on my macOS? My "`Partial ROCs, omission rates, and AICcs calculation, please wait...`" progress in RStudio stays on 0 % indefinitely. So something is clearly wrong.

**Comment by HNKamau** [comment]
I am having similar challenges - Is there a solution to the above?

**Comment by kamaulindhardt** [comment]
**Dear authors of kuenm** @marlonecobos 

Have you any updates on this issue? Is it something you see only in Mac OS or across all operating systems?

Best regards,
Kamau

**Comment by kamaulindhardt** [comment]
Thank you @marlonecobos for your reply! 

It is a while I ran into this problem – but I will re-try it taking your feedback into account.,
