### ISSUE TITLE
Having issue with MOP

### ISSUE THREAD

**Issue by Pritam31** [marlonecobos/kuenm#26]
Hi Marlon,
I ran this codes 
kuenm_mmop(G.var.dir = gvars, M.var.dir = mvars, sets.var = sets_var, 
           out.mop = outmop, percent = 10, comp.each = 2000, 
           parallel = TRUE)
and got this error
Error in kuenm_mmop(G.var.dir = gvars, M.var.dir = mvars, sets.var = sets_var,  : 
  **Argument is.swd is not defined.** but I have not used swd anywhere above.

**Comment by marlonecobos** [comment]
Please see the options in the function's documentation. If you did not use swd format, set the argument to FALSE.

**Comment by Pritam31** [comment]
Hi,
is_swd <- FALSE
> outmop <- "MOP_results"
> kuenm_mmop(G.var.dir = gvars, M.var.dir = mvars, is.swd = is_swd, sets.var = "Set_5",
+            out.mop = outmop, percent = 10, comp.each = 2000, 
+            parallel = TRUE)
 I ran above script and got below result
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
