### ISSUE TITLE
Fitting PPM in maxent with KUENM??

### ISSUE THREAD

**Issue by SDMENM** [marlonecobos/kuenm#37]
Hey Good people, 
What's the default for "addsamplestobackground" and "removeduplicates" while calling maxent in kuenm, specifically for kuenm_cal function? 

I think samples are not added to background after reading the issues here, but I am not sure about default removeduplicates function. 
I am asking because these two arguments are important to customize for fitting PPM via maxent, and I am curious if I can do this with kuenm? I know it can be done with dismo as in Renner et al., 2015 supplementary material. 
Thanks..

**Comment by marlonecobos** [comment]
The default options are the same as in Maxent. You can change them using `args`.
