### ISSUE TITLE
mx1000m jar limit

### ISSUE THREAD

**Issue by njvelasc** [marlonecobos/kuenm#41]
Hi, I have been using kuenm for a while and I'm wondering if there is a way to allocate more memory (as you can do with Maxent.bat), as when I run the program I prefer to leave my laptop only doing this. I see in the cmd.exe that the heap size is mx1000m jar but I don't find a way to increase the maximum.

Any options?

**Comment by marlonecobos** [comment]
Check the argument `max.memory `  in the functions that run maxent.
