### ISSUE TITLE
Issues with kuenm_ceval()

### ISSUE THREAD

**Issue by Jendritzki** [marlonecobos/kuenm#43]
Dear Marlon and community,

I am also experiencing issues when evaluating the candidate models, as the progress bar is stuck with 0.4%. I have read through the other issues comments and checked back with what I have. I noticed that in my candidate models, only for a few a batch file is created, whereas for the others there is no batch file. Do you have any idea why this could be the case? I have cleared my laptop so that storage space should not be the problem.
<img width="559" alt="Screenshot 2022-06-09 105606" src="https://user-images.githubusercontent.com/107179371/172807726-54e16fc0-0079-4ab7-b585-d8938ae09096.png">

**Comment by yutingzhouBJFU** [comment]
Yes, I have the same bug, and the process bar is stuck with 0.8% for a whole nighe, @marlonecobos please kindly help check what's wrong with it?

**Comment by marlonecobos** [comment]
Here is my answer to a similar question...
https://github.com/marlonecobos/kuenm/issues/7#issuecomment-651306066

**Comment by yutingzhouBJFU** [comment]
您的来信已经收到，我将尽快阅读回复，祝好！

**Comment by yutingzhouBJFU** [comment]
您的来信已经收到，我将尽快阅读回复，祝好！
