### ISSUE TITLE
kuenm_cal_swd: Error in n.par(lambdas) : could not find function "n.par"

### ISSUE THREAD

**Issue by yessikr16** [marlonecobos/kuenm#45]
hello Marlon, I have a problem when executing kuenm_cal_swd it does not generate the condidate models and in the end I get the following message Error in n.par(lambdas) : could not find function "n.par", maybe you have a solution for this mistake.
![kuenm](https://user-images.githubusercontent.com/109847137/180596739-5a9f2bc4-6820-4b77-b27e-3bf562f66b0a.PNG)

**Comment by marlonecobos** [comment]
The issue should be solved now. Thanks for letting me know.
