### ISSUE TITLE
kuenm is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by joao-rafael-soares** [marlonecobos/kuenm#5]
Recently I tried to install Kuenm but I've got this message error saying "Warning in install.packages : package ‘kuenm’ is not available (for R version 3.6.2)". Anyone with the same issue?

**Comment by marlonecobos** [comment]
Hi, kuenm is not in CRAN yet. You cannot use install.packages. Use install_github from devtools, you can find indications here https://github.com/marlonecobos/kuenm#installing-the-package

**Comment by joao-rafael-soares** [comment]
Thank you for your support marlonecobos. I didn't realize that. Now it worked.
