### ISSUE TITLE
How to specify categorical variables

### ISSUE THREAD

**Issue by nanqiuxun** [marlonecobos/kuenm#52]
Hello

I have a problem. I have a categorical variable in my environment variable. How do I indicate that my variable is categorical and not continuous in the generated candidate model and final model? I see the model results that default all environment variables to continuous type. Is there a variable in kuenm function similar to one in ENMeval that is categoricals= "env1" used to specify categorical variables?

Thanks!

**Comment by nanqiuxun** [comment]
Hi,I need some help! There are  two categories variables in my environmental variables，how should  I express it correctly by using togglelayertype? I have tried lots of methods to tell the computer but it still could not understand.
Thanks!
![image](https://user-images.githubusercontent.com/120238350/227869801-0740142a-1d38-4d0b-bf0f-0ae094dbed0e.png)
![image](https://user-images.githubusercontent.com/120238350/227870876-09fd70ef-0bd5-4398-968b-cfc267284ecd.png)

**Comment by leibar4** [comment]
Did you manage to solve this problem? If so could you please post the solution?

**Comment by nanqiuxun** [comment]
> 你设法解决这个问题了吗？如果是这样，您可以发布解决方案吗？

Sorry, I haven't solved this yet, so I changed the categorical variables to other continuous variables.
