### ISSUE TITLE
"occ.ind" in kuenm_feval function

### ISSUE THREAD

**Issue by KavyPathirana** [marlonecobos/kuenm#54]
How to deal with the function "kuemn_feval" if I do not have individual occurrence data? 

fin_eval <- kuenm_feval(path = mod_dir, occ.joint = occ_joint, occ.ind = **?????**, 
                        replicates = replicates, out.eval = out_feval, 
                        threshold = threshold, rand.percent = rand_percent,
                        iterations = iterations)

**Comment by marlonecobos** [comment]
Most people don't have this type of data. You can go through the rest of the process without problems though.
