### ISSUE TITLE
kuenm_mmop : error

### ISSUE THREAD

**Issue by masa183** [marlonecobos/kuenm#55]
When running MOP analysis using kuenm_mmop, I got the following error.

- Warning: the condition has length > 1 and only the first element will be used
- Warning: NOT UPDATED FOR PROJ >= 6

I did MOP like this

```
is_swd <- FALSE
sets_var <- c("Set_7")
out_mop <- "MOP_results"
percent <- 10
paral <- FALSE
```

```
kuenm_mmop(G.var.dir = G_var_dir, M.var.dir = M_var_dir, is.swd = is_swd,
           sets.var = sets_var, out.mop = out_mop, percent = percent, 
           parallel = paral)

```
I got the tiff file of MOP result , however, the value of the result is 0. 
Do you have any idea what the problem is?
Many thanks, 

Masa

**Comment by Kafash68** [comment]
I have also same Issue, could you solve it?

**Comment by marlonecobos** [comment]
This means that one or multiple of your projection variables are completely different from your calibration variables. Check the values in the layers to make sure they are comparable. This is data-related, not kuenm, closing this.
