### ISSUE TITLE
Broken CRAN dependency - hier.part

### ISSUE THREAD

**Issue by ascanioalfredoa** [marlonecobos/kuenm#56]
Hi Marlon,

I was trying to use kuenm for some MOP analysis and when trying to install it seems that the hier.part package (a dependency) was removed from CRAN early this month (see https://cran.r-project.org/web/packages/hier.part/index.html).

I don't know if it's possible to update the dependencies to install the github development version in the meantime https://github.com/cran/hier.part. After I did that, the kuenm installation worked.

**Comment by marlonecobos** [comment]
The new version of kuenm does not import hier.part. I deprecated functions that used that package for the moment.
