### ISSUE TITLE
Maxent is skipping too many samples

### ISSUE THREAD

**Issue by o92dupes** [marlonecobos/kuenm#57]
Hello Mr Cobos.

Im having some issues with some of the functions. I hope you can help me to solve them:

1st  I noticed that my maxent process has too many warnings.
 
Sorry but I cannot find a solution. Do you have any idea why this is happening? I tried a lot of things but they are still the same (I thought it could be a coordinate problem or my system configuration...). Should I change the training proportion?
Thanks again and sorry to bother you.

![Maxent skipping](https://user-images.githubusercontent.com/62184802/231034016-e2155600-5af8-4d8c-9897-138dc0bb997b.PNG)

Regards,
Sergio.

**Comment by marlonecobos** [comment]
This is basic Maxent processing and it is related to your data. If the records are outside the borders of the raster layers that contain data, those samples will not be used. Check your data to solve this problem. This is not related to kuenm functionalities.
