### ISSUE TITLE
bug in kuenm_varcomb()

### ISSUE THREAD

**Issue by cladesinspace** [marlonecobos/kuenm#6]
# Line 142 

setTxtProgressBar(pb, i) 
 i - assuming - is not defined. Results in a error.
Error in setTxtProgressBar(pb, i) : object 'i' not found

Changing  it to "k" appears to work. 
Function executes and creates a folder,  M_variables, with the sets in different subfolders

Thanks for the all the efforts in making modelling accessible!
All the best
Vijay

**Comment by marlonecobos** [comment]
Thanks, I just fixed it.
