### ISSUE TITLE
evaluation "kuenm_ceval" doesn't work

### ISSUE THREAD

**Issue by luaneazeredo** [marlonecobos/kuenm#7]
Hi Marlon
I just watched your presentation in the ENM2020 course. Congratulations
I'm trying to do the exercise of the ascii script but when I try to do the evaluation candidate models the evaluation models starts running but it doesn't stop. I left my computer on along the day and the process didn't pass 1,11%. 
I tried in two different computers and tha same thing happened on both. 
I would like to know if that is happening to someone else or whether there is a solution.
Thanks

**Comment by marlonecobos** [comment]
@luaneazeredo I am going to need more details to be able to help. Please send me an email with them to fix your problem.

**Comment by luaneazeredo** [comment]
> Hi, Marlon
I jusot saw your answer on github repository about my question and now i'm writing to detail what is happening. 
I'm following your script Exercise_ascii.r 

#-------------------------------------------------------------------------------
# loading the package
library(kuenm)

# setting working directory (CHANGE IT ACCORDING TO YOUR NEEDS)
setwd("C:/Users/Marlon/Desktop/ENM_2020/Exercise_ascii")
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# preparing data
## splitting training and testing records (complete the code)
help(kuenm_occsplit)

occs <- read.csv("aame.csv")

set.seed(1)
split <- kuenm_occsplit(occ = occs, train.proportion = 0.7, method = "random",
                        save = TRUE, name = "occ") #separa dados para teste e treino

## preparing sets of variables (complete the code)
help(kuenm_varcomb)

vs <- kuenm_varcomb(var.dir = "Variables", out.dir = "M_variables", min.number = 3,
                    in.format = "ascii", out.format = "ascii")

#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# calibration
## candidate model creation (complete the code)
help(kuenm_cal)

oj <- "occ_joint.csv"
otr <- "occ_train.csv"
mvars <- "M_variables"
bcal <- "batch_cal"
candir <- "Candidate_models"
regm <- c(0.1, 0.25, 0.5, 1, 2, 4)
fclas <- c("lq", "lqp", "q")
mxpath <- "C:/Maxent/3.4.1"

kuenm_cal(occ.joint = oj, occ.tra = otr, M.var.dir = mvars, #funcao de calibracao
          batch = bcal, out.dir = candir, max.memory = 1000,
          reg.mult = regm, f.clas = fclas, args = NULL,
          maxent.path = mxpath, wait = FALSE, run = TRUE) #a funcao wait=false eh para que vc possa continuar a mexer no r, pois a calibracao esta sendo feita em outra janela


## evaluation of candidate models (complete the code)
help(kuenm_ceval)

ote <- "occ_test.csv"
cresdir <- "Calibration_results"

**kuenm_ceval(path = candir, occ.joint = oj, occ.tra = ote,
            occ.test = ote, batch = bcal, out.eval = cresdir,
            threshold = 5, rand.percent = 50, iterations = 500,
            kept = TRUE, selection = "OR_AICc", parallel.proc = FALSE)**

When I come to this line (hightlighted in bold), the evaluation process starts, but doesn't finish. I attached a picture to show the console and the process
I took the computer on the all night but the process didn't complete. 
The Maxent is installed, and I know what i'm doing wrong.

I grateful since always, if you could help me
Sincerely, 

![2020-06-29 (1)](https://user-images.githubusercontent.com/55959722/86014280-80125580-b9f6-11ea-9daf-a65585b047c3.png)

**Comment by luaneazeredo** [comment]
Hi, Marlon
I jusot saw your answer on github repository about my question and now i'm writing to detail what is happening. 
I'm following your script Exercise_ascii.r 

#-------------------------------------------------------------------------------
# loading the package
library(kuenm)

# setting working directory (CHANGE IT ACCORDING TO YOUR NEEDS)
setwd("C:/Users/Marlon/Desktop/ENM_2020/Exercise_ascii")
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# preparing data
## splitting training and testing records (complete the code)
help(kuenm_occsplit)

occs <- read.csv("aame.csv")

set.seed(1)
split <- kuenm_occsplit(occ = occs, train.proportion = 0.7, method = "random",
                        save = TRUE, name = "occ") #separa dados para teste e treino

## preparing sets of variables (complete the code)
help(kuenm_varcomb)

vs <- kuenm_varcomb(var.dir = "Variables", out.dir = "M_variables", min.number = 3,
                    in.format = "ascii", out.format = "ascii")

#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# calibration
## candidate model creation (complete the code)
help(kuenm_cal)

oj <- "occ_joint.csv"
otr <- "occ_train.csv"
mvars <- "M_variables"
bcal <- "batch_cal"
candir <- "Candidate_models"
regm <- c(0.1, 0.25, 0.5, 1, 2, 4)
fclas <- c("lq", "lqp", "q")
mxpath <- "C:/Maxent/3.4.1"

kuenm_cal(occ.joint = oj, occ.tra = otr, M.var.dir = mvars, #funcao de calibracao
          batch = bcal, out.dir = candir, max.memory = 1000,
          reg.mult = regm, f.clas = fclas, args = NULL,
          maxent.path = mxpath, wait = FALSE, run = TRUE) #a funcao wait=false eh para que vc possa continuar a mexer no r, pois a calibracao esta sendo feita em outra janela


## evaluation of candidate models (complete the code)
help(kuenm_ceval)

ote <- "occ_test.csv"
cresdir <- "Calibration_results"

kuenm_ceval(path = candir, occ.joint = oj, occ.tra = ote,
            occ.test = ote, batch = bcal, out.eval = cresdir,
            threshold = 5, rand.percent = 50, iterations = 500,
            kept = TRUE, selection = "OR_AICc", parallel.proc = FALSE)

When I come to this line (hightlighted in bold), the evaluation process starts, but doesn't finish. I attached a picture to show the console and the process
I took the computer on the all night but the process didn't complete. 
The Maxent is installed, and I don't know what i'm doing wrong.

I grateful since always, if you could help me
Sincerely, 


![2020-06-29 (1)](https://user-images.githubusercontent.com/55959722/86015178-9ec51c00-b9f7-11ea-97ad-1815faed82a3.png)

**Comment by marlonecobos** [comment]
OK, I used your script and the data that was shared with the example (the one you are using). I did not get any error and the evaluation of candidate models run perfectly. I think that your problem is related to Maxent. Please make sure your candidate models were produced and are in your directory. If there are no models there, the evaluation process will be waiting for them to be produced and won't advance. 

Inside your working directory in the folder with candidate models, you should have something like this for each of the subfolders you obtain. 

![image](https://user-images.githubusercontent.com/19596631/86045759-a7c2e700-ba11-11ea-9aba-239553835aa8.png)

If you don't have these files, check the maxent.log file that should be there, telling you what went wrong. If you don't even have that file, the problem should be that you did not define well the path for Maxent. make sure that the file maxent.jar is in the path you defined in the script. I saw that you have the same path for Maxent that was used in the example, please make sure that it exists on your computer. Mine is here, but make sure you have it.

![image](https://user-images.githubusercontent.com/19596631/86046172-5e26cc00-ba12-11ea-91c7-db23f2bbd2a8.png)

**Comment by luaneazeredo** [comment]
Dear Marlon. Thanks for your patience and attention. I moved my files to a nonsychronizing folder and it finally worked! Apparently Maxent wasn't able to cacth the files because of the cloud synchronization. 
Thks again!

**Comment by marlonecobos** [comment]
Perfect, closing this.
