### ISSUE TITLE
Error with kuenm_mod

### ISSUE THREAD

**Issue by JennaRain** [marlonecobos/kuenm#8]
Hi! 
I have made it to the kuenm_mod step but when I run it, I get the following error:
Show in New WindowClear OutputExpand/Collapse Output
"""
Error in kuenm_mod(occ.joint = occ_joint, M.var.dir = M_var_dir, out.eval = out_eval, : G_variables does not exist in the working directory, check folder name or its existence.
"""

The previous step using kuenm_ceval appeared to have worked as it created the html file under calibration_results directory.  So I think everything has worked correctly so far.

Here is the code I ran to prepare the argument for the kuenm_mod function:
"""
```{r, eval=FALSE}
batch_fin <- "Final_models"
mod_dir <- "Final_Models"
rep_n <- 10
rep_type <- "Bootstrap"
jackknife <- FALSE
out_format <- "logistic"
project <- TRUE
G_var_dir <- "G_variables"
ext_type <- "all"
write_mess <- FALSE
write_clamp <- FALSE
wait1 <- FALSE
run1 <- TRUE
args <- NULL
"""

I am not sure what I am missing between the ceval and the mod step. 

Thanks so much for any guidance.  My lab and I are using this code for 3 separate research projects and we are very excited to be implementing it. 
Jenna

**Comment by pablofcuervo** [comment]
Hi Jenna,
"kuenm_ceval" doesn't require to define G_variables. "kuenm_mod" requires for you to define G_variables in order to transfer the model to geography and/or time other than the one used for calibration. You should include it inside the species folder.

Hope this helps

Pablo

**Comment by JennaRain** [comment]
Thank you! That helps a lot!

On Jul 14, 2020, at 3:53 PM, pablofcuervo <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Jenna,
"kuenm_ceval" doesn't require to define G_variables. "kuenm_mod" requires for you to define G_variables in order to transfer the model to geography and/or time other than the one used for calibration. You should include it inside the species folder.

Hope this helps

Pablo

**Comment by pablofcuervo** [comment]
Glad to help! Let me know if you need further help
Regards

**Comment by marlonecobos** [comment]
@JennaRain, please let me know if you were able to solve the problem. 

I was not able to see what the problem is based on your initial message. I just can say that when you are using kuenm_mod, you define the argument "project" as TRUE only when model projections are needed. Additionally, when you set project = TRUE, you have to define the argument G.var.dir, which is the name of the folder containing the sets of variables and scenarios for model projection.
