### ISSUE TITLE
Issue with kuenm_mod_swd

### ISSUE THREAD

**Issue by pablofcuervo** [marlonecobos/kuenm#9]
Hi,
I found an issue with the function "kuem_mod_swd" when "project = FALSE"
Line 127 "G.dirs <- rep(G.dirs, each = rtimes)" should go inside "if (project == TRUE)" after line 128. Otherwise it shows the following message:
"Error in kuenm::kuenm_mod_swd(occ.joint = oj, back.dir = back, out.eval = cresdir,: objeto 'G.dirs' no encontrado"

**Comment by marlonecobos** [comment]
Hi, 
Thanks, you are right. The issue is now solved.
